layout_spectrum: 0.8893858694256569
typography_spectrum: 0.1555388028014193
color:
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  brandStrength: 0.20379882605128583
  lightness: 0.46955682863840964
  saturation: 0.11782245098345794
  rhythmicContrast: 0.12670393924505477
github: true
opengraph: {}
analytics:
  facebook: ''
  google: ''
  twitter: ''
author:
  name: Steve GW
  email: stevegwusa@gmail.com
name: Steve GW Today
cta: {}
navigation:
  - name: Game Art
    url: 'http://thegrid.ai/stevegw-game-art'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cd369eba-0ef6-4f02-870b-65e75a986db8.ico
title: Art  by Steve GW
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/60188c70-3000-42c5-bc36-c38b8144d9d8.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/60188c70-3000-42c5-bc36-c38b8144d9d8.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Art Explorations
purpose:
  - type: contact
    url: 'mailto:stevegwusa@gmail.com'
    label: Contact me
