favicon: null
name: sketchytime
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9483170215971768
  brandStrength: 0.5090727747883648
  rhythmicContrast: 0.75
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  lightness: 0.4714933042414486
typography_spectrum: 0.28125
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
