typography_spectrum: 0.28125
color:
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  brandStrength: 0.5090727747883648
  lightness: 0.4714933042414486
  rhythmicContrast: 0.75
  saturation: 0.9483170215971768
opengraph: {}
layout_spectrum: 0
analytics: {}
name: sketchytime
cta: {}
navigation:
  - name: Ausgust Show
    url: 'https://thegrid.ai/sketchytime-aug-show/'
    type: external
purpose: []
