name: Steve GW Today
layout_spectrum: 0.019203792326152325
typography_spectrum: 0.3487208364531398
cta: {}
analytics:
  facebook: ''
  google: ''
  twitter: ''
opengraph: {}
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.24798112316057086
  lightness: 0.005521420622244477
  saturation: 0.38509206427261233
  rhythmicContrast: 0.10317498096264899
purpose: []
title: Art  by Steve GW
author:
  name: Steve GW
  email: stevegwusa@gmail.com
navigation:
  - name: Pastels
    url: 'http://thegrid.ai/sketchytime-pastels'
    type: external
  - name: Game Art
    url: 'http://thegrid.ai/stevegw-game-art'
    type: external
  - name: Human Form
    url: 'http://thegrid.ai/stevegw-human-form'
    type: external
  - name: Aug Art Show
    url: 'http://thegrid.ai/stevegw-aug-artshow'
    type: external
  - name: About
    url: 'http://thegrid.ai/stevegw-about/'
    type: external
