layout_spectrum: 0.5875427437948044
typography_spectrum: 0.4049092625613592
color:
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  brandStrength: 0.20334184565858013
  lightness: 0.4675480147901148
  saturation: 0.1129559077021878
  rhythmicContrast: 0.12276290176270327
github: true
opengraph: {}
analytics:
  facebook: ''
  google: ''
  twitter: ''
author:
  name: Steve GW
  email: stevegwusa@gmail.com
name: Steve GW Today
cta: {}
navigation:
  - name: Game Art
    url: 'http://thegrid.ai/stevegw-game-art'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cd369eba-0ef6-4f02-870b-65e75a986db8.ico
title: Art  by Steve GW
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/596bae51-e722-4b98-8c26-7e91f446ab95.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/596bae51-e722-4b98-8c26-7e91f446ab95.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Art Explorations
purpose:
  - type: contact
    url: 'mailto:stevegwusa@gmail.com'
    label: Contact me
