layout_spectrum: 0.789214288575833
typography_spectrum: 0.6273414009161257
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.853040613242342
  lightness: 0.21379681617879115
  saturation: 0.9927736280007416
  rhythmicContrast: 0.12379705133082547
opengraph: {}
analytics:
  facebook: ''
  google: ''
  twitter: ''
author:
  name: Steve GW
  email: stevegwusa@gmail.com
name: Steve GW Today
cta: {}
navigation:
  - name: Pastels
    url: 'http://thegrid.ai/sketchytime-pastels'
    type: external
  - name: Game Art
    url: 'http://thegrid.ai/stevegw-game-art'
    type: external
  - name: Human Form
    url: 'http://thegrid.ai/stevegw-human-form'
    type: external
  - name: Aug Art Show
    url: 'http://thegrid.ai/stevegw-aug-artshow'
    type: external
  - name: About
    url: 'http://thegrid.ai/stevegw-about/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cd369eba-0ef6-4f02-870b-65e75a986db8.ico
title: Art  by Steve GW
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/596bae51-e722-4b98-8c26-7e91f446ab95.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/596bae51-e722-4b98-8c26-7e91f446ab95.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Art Explorations using both traditional methods and Digital
purpose:
  - type: contact
    url: 'mailto:stevegwusa@gmail.com'
    label: Contact me
github: true
