typography_spectrum: 0.32129533775150776
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.06296082097105682
  lightness: 0.21688015176914632
  rhythmicContrast: 0.26289014238864183
  saturation: 0.24055635510012507
opengraph: {}
layout_spectrum: 0.5335681384894997
analytics: {}
author:
  email: stevegwusa@gmail.com
  name: Steve GW
name: Steve GW Today
cta: {}
navigation:
  - name: August Show
    url: 'https://thegrid.ai/sketchytime-aug-show/'
    type: external
  - name: Pastels
    url: 'http://thegrid.ai/sketchytime-pastels'
    type: external
  - name: About
    url: 'http://thegrid.ai/stevegw-about/'
    type: external
title: Art  by Steve GW
description: To obverse is to Grow
purpose: []
