layout_spectrum: 0.8917330509997757
typography_spectrum: 0.4003119457402442
color:
  brandColors:
    - '#565D70'
    - '#E01B24'
    - '#9AA4AE'
    - '#E9DAB1'
    - '#C6A100'
  brandStrength: 0.8748715015458367
  lightness: 0.3483903857451486
  saturation: 0.18346268565246449
  rhythmicContrast: 0.4281737924016791
github: true
opengraph: {}
analytics:
  facebook: ''
  google: ''
  twitter: ''
author:
  name: Steve GW
  email: stevegwusa@gmail.com
name: Steve GW Today
cta: {}
navigation:
  - name: Game Art
    url: 'http://thegrid.ai/stevegw-game-art'
    type: external
  - name: Human Form
    url: 'http://thegrid.ai/stevegw-human-form'
    type: external
  - name: Aug Art Show
    url: 'https://thegrid.ai/augustshow'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cd369eba-0ef6-4f02-870b-65e75a986db8.ico
title: Art  by Steve GW
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/596bae51-e722-4b98-8c26-7e91f446ab95.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/596bae51-e722-4b98-8c26-7e91f446ab95.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Art Explorations using both traditional and Digital approaches
purpose:
  - type: contact
    url: 'mailto:stevegwusa@gmail.com'
    label: Contact me
